var languageStats = {
    "data":[
        {
            "language":"Ruby",
            "repositories":33683
        },
        {
            "language":"JavaScript",
            "repositories":9642
        },
        {
            "language":"Python",
            "repositories":7128
        },
        {
            "language":"Perl",
            "repositories":4556
        },
        {
            "language":"C",
            "repositories":4219
        },
        {
            "language":"PHP",
            "repositories":3961
        },
        {
            "language":"Java",
            "repositories":3342
        },
        {
            "language":"C++",
            "repositories":2896
        },
        {
            "language":"Objective-C",
            "repositories":1773
        },
        {
            "language":"Shell",
            "repositories":1250
        },
        {
            "language":"C#",
            "repositories":1022
        },
        {
            "language":"Emacs Lisp",
            "repositories":976
        },
        {
            "language":"VimL",
            "repositories":917
        },
        {
            "language":"Erlang",
            "repositories":790
        },
        {
            "language":"Lua",
            "repositories":589
        },
        {
            "language":"Haskell",
            "repositories":572
        },
        {
            "language":"ActionScript",
            "repositories":473
        },
        {
            "language":"Scala",
            "repositories":396
        },
        {
            "language":"Common Lisp",
            "repositories":348
        },
        {
            "language":"Clojure",
            "repositories":325
        },
        {
            "language":"CSS",
            "repositories":263
        },
        {
            "language":"HTML",
            "repositories":199
        },
        {
            "language":"Scheme",
            "repositories":191
        },
        {
            "language":"Groovy",
            "repositories":166
        },
        {
            "language":"OCaml",
            "repositories":104
        },
        {
            "language":"Objective-J",
            "repositories":60
        },
        {
            "language":"R",
            "repositories":58
        },
        {
            "language":"Visual Basic",
            "repositories":54
        },
        {
            "language":"TeX",
            "repositories":46
        },
        {
            "language":"D",
            "repositories":39
        },
        {
            "language":"Parrot",
            "repositories":35
        },
        {
            "language":"Tcl",
            "repositories":31
        },
        {
            "language":"Nu",
            "repositories":30
        },
        {
            "language":"Puppet",
            "repositories":30
        },
        {
            "language":"Io",
            "repositories":28
        },
        {
            "language":"Arc",
            "repositories":28
        },
        {
            "language":"Perl6",
            "repositories":27
        },
        {
            "language":"Prolog",
            "repositories":27
        },
        {
            "language":"Assembly",
            "repositories":24
        },
        {
            "language":"FORTRAN",
            "repositories":23
        },
        {
            "language":"Pure Data",
            "repositories":22
        },
        {
            "language":"XSLT",
            "repositories":20
        },
        {
            "language":"SuperCollider",
            "repositories":18
        },
        {
            "language":"Matlab",
            "repositories":17
        },
        {
            "language":"ASP",
            "repositories":14
        },
        {
            "language":"ColdFusion",
            "repositories":14
        },
        {
            "language":"VHDL",
            "repositories":11
        },
        {
            "language":"Pascal",
            "repositories":11
        },
        {
            "language":"Go",
            "repositories":10
        },
        {
            "language":"Smalltalk",
            "repositories":10
        },
        {
            "language":"Makefile",
            "repositories":9
        },
        {
            "language":"F#",
            "repositories":9
        },
        {
            "language":"AutoHotkey",
            "repositories":8
        },
        {
            "language":"Verilog",
            "repositories":8
        },
        {
            "language":"Forth",
            "repositories":7
        },
        {
            "language":"CoffeeScript",
            "repositories":7
        },
        {
            "language":"Self",
            "repositories":7
        },
        {
            "language":"Eiffel",
            "repositories":6
        },
        {
            "language":"Racket",
            "repositories":6
        },
        {
            "language":"Processing",
            "repositories":5
        },
        {
            "language":"AGS Script",
            "repositories":5
        },
        {
            "language":"Ragel in Ruby Host",
            "repositories":4
        },
        {
            "language":"LilyPond",
            "repositories":4
        },
        {
            "language":"Groff",
            "repositories":4
        },
        {
            "language":"PowerShell",
            "repositories":4
        },
        {
            "language":"Factor",
            "repositories":4
        },
        {
            "language":"AppleScript",
            "repositories":3
        },
        {
            "language":"Rust",
            "repositories":3
        },
        {
            "language":"Standard ML",
            "repositories":3
        },
        {
            "language":"Haxe",
            "repositories":3
        },
        {
            "language":"ooc",
            "repositories":3
        },
        {
            "language":"Vala",
            "repositories":2
        },
        {
            "language":"Cucumber",
            "repositories":2
        },
        {
            "language":"PLpgSQL",
            "repositories":2
        },
        {
            "language":"TypeScript",
            "repositories":2
        },
        {
            "language":"Augeas",
            "repositories":2
        },
        {
            "language":"Pike",
            "repositories":2
        },
        {
            "language":"XML",
            "repositories":2
        },
        {
            "language":"Gosu",
            "repositories":2
        },
        {
            "language":"Awk",
            "repositories":2
        },
        {
            "language":"Elixir",
            "repositories":2
        },
        {
            "language":"XS",
            "repositories":2
        },
        {
            "language":"CMake",
            "repositories":1
        },
        {
            "language":"Liquid",
            "repositories":1
        },
        {
            "language":"Nemerle",
            "repositories":1
        },
        {
            "language":"Scilab",
            "repositories":1
        },
        {
            "language":"BlitzMax",
            "repositories":1
        },
        {
            "language":"XProc",
            "repositories":1
        },
        {
            "language":"ApacheConf",
            "repositories":1
        },
        {
            "language":"OpenEdge ABL",
            "repositories":1
        },
        {
            "language":"Arduino",
            "repositories":1
        },
        {
            "language":"Gnuplot",
            "repositories":1
        },
        {
            "language":"Mercury",
            "repositories":1
        },
        {
            "language":"Batchfile",
            "repositories":1
        },
        {
            "language":"Eagle",
            "repositories":1
        },
        {
            "language":"NSIS",
            "repositories":1
        },
        {
            "language":"Objective-C++",
            "repositories":1
        },
        {
            "language":"SQL",
            "repositories":1
        },
        {
            "language":"ChucK",
            "repositories":1
        },
        {
            "language":"KiCad",
            "repositories":1
        },
        {
            "language":"Swift",
            "repositories":1
        },
        {
            "language":"GAP",
            "repositories":1
        },
        {
            "language":"Rebol",
            "repositories":1
        },
        {
            "language":"Turing",
            "repositories":1
        },
        {
            "language":"Coq",
            "repositories":1
        },
        {
            "language":"Max/MSP",
            "repositories":1
        },
        {
            "language":"nesC",
            "repositories":1
        },
        {
            "language":"PostScript",
            "repositories":1
        },
        {
            "language":"Bro",
            "repositories":1
        },
        {
            "language":"IDL",
            "repositories":1
        },
        {
            "language":"Smarty",
            "repositories":1
        },
        {
            "language":"Ada",
            "repositories":1
        }
    ]
};